pipeline {
    agent {
        docker {
            image 'node:12.16' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'yarn install' 
            }
        }
    }
}